<?xml version="1.0"?>
<robot name="simple_eva" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<!-- Import variables -->	
	<xacro:include filename="$(find simple_eva_description)/urdf/variables.xacro"/>
	<!-- Import macros -->
	<xacro:include filename="$(find simple_eva_description)/urdf/macros.xacro"/>
	<!-- Import gazebo elements -->
	<xacro:include filename="$(find simple_eva_description)/urdf/simple_robot.gazebo"/>
	
	<!-- Used for fixing robot to Gazebo world -->
	<link name="world"/>
	
	<joint name="fixed" type="fixed">
		<parent link="world"/>
		<child link="link1"/>
	</joint>
	
	<!-- 1st link -->
	<link name="link1">
		<xacro:box_inertial m="${m_total*(l1_l/l_total)}" l="${l1_l}" d="${l1_d}" w="${l1_w}"/>
		<xacro:box_geometry name="link1" l="${l1_l}" d="${l1_d}" w="${l1_w}" XYZ="0 0 ${l1_l/2}" RPY="0 0 0"/>
	</link>
	
	<!-- 1st joint --> 
	<joint name="joint1" type="revolute">
		<parent link="link1"/>
		<child link="link2"/>
		<xacro:joint_limits upper="179" lower="-179"/>
		<axis xyz="0 0 1"/>
		<origin xyz="0 0 ${l1_l}" rpy="0 0 0"/>
	</joint>
	
	<!-- 2nd link -->
	<link name="link2">
		<xacro:cylinder_inertial m="${m_total*(l2_l/l_total)}" l="${l2_l}" r="${l2_r}"/>
		<xacro:cylinder_geometry name="link2" l="${l2_l}" r="${l2_r}" XYZ="0 ${l2_r} ${l2_l/2}" RPY="0 0 0"/>
	</link>
	
	<!-- 2nd joint -->
	<joint name="joint2" type="revolute">
		<parent link="link2"/>
		<child link="link3"/>
		<xacro:joint_limits upper="70" lower="-155"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 ${l2_l}" rpy="0 0 0"/>
	</joint>
	
	<!-- 3rd link -->
	<link name="link3">
		<xacro:cylinder_inertial m="${m_total*(l3_l/l_total)}" l="${l3_l}" r="${l3_r}"/>
		<xacro:cylinder_geometry name="link3" l="${l3_l}" r="${l3_r}" XYZ="0 ${-1*l3_r} ${l2_l}" RPY="0 0 0"/>
	</link>
	
	<!-- 3rd joint -->
	<joint name="joint3" type="revolute">
		<parent link="link3"/>
		<child link="link4"/>
		<xacro:joint_limits upper="45" lower="-160"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 ${l3_l}" rpy="0 0 0"/>
	</joint>
	
	<!-- 4th link -->
	<link name="link4">
		<xacro:cylinder_inertial m="${m_total*(l4_l/l_total)}" l="${l4_l}" r="${l4_r}"/>
		<xacro:cylinder_geometry name="link4" l="${l4_l}" r="${l4_r}" XYZ="0 ${l4_r} ${l4_l/2}" RPY="0 0 0"/>
	</link>
	
	<!-- 4th joint -->
	<joint name="joint4" type="revolute">
		<parent link="link4"/>
		<child link="link5"/>
		<xacro:joint_limits upper="179" lower="-179"/>
		<axis xyz="0 0 1"/>
		<origin xyz="0 0 ${l4_l}" rpy="0 0 0"/>
	</joint>
	
	<!-- 5th link -->
	<link name="link5">
		<xacro:cylinder_inertial m="${m_total*(l5_l/l_total)}" l="${l5_l}" r="${l5_r}"/>
		<xacro:cylinder_geometry name="link5" l="${l5_l}" r="${l4_r}" XYZ="0 0 ${l5_l/2}" RPY="0 0 0"/>
	</link>
	
	<!-- 5th joint -->
	<joint name="joint5" type="revolute">
		<parent link="link5"/>
		<child link="link6"/>
		<xacro:joint_limits upper="10" lower="-155"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 ${l5_l}" rpy="0 0 0"/>
	</joint>
	
	<!-- 6th link -->
	<link name="link6">
		<xacro:box_inertial m="${m_total*(l6_l/l_total)}" l="${l6_l}" d="${l6_d}" w="${l6_w}"/>
		<xacro:box_geometry name="link6" l="${l6_l}" d="${l6_d}" w="${l6_w}" XYZ="0 0 ${l6_l/2}" RPY="0 0 0"/>
	</link>		
</robot>